### PR TITLE
Update CLAP to 1.2.1

### PR DESCRIPTION
**Pull request by Jengamon**

### CODE REVIEW

**Comment by Jengamon** [comment]
bump?

**Comment by dailybeats** [comment]
It would be nice to merge this. I could help with the review if necessary.

**Comment by micahrj** [comment]
Can I request that the 1.2.1 changes be moved into a separate PR?

**Comment by Jengamon** [comment]
> Can I request that the 1.2.1 changes be moved into a separate PR?

Now in #34 (well, the 1.2.0 changes)

**Pull request closed without merging**
